function p_seg1_bottom = find_seg1_bottom(l1,seg1_top_1,seg1_top_2,seg1_top_3,theta1_1,theta1_2)
%FIND_SEG1_BOTTOM
%    P_SEG1_BOTTOM = FIND_SEG1_BOTTOM(L1,SEG1_TOP_1,SEG1_TOP_2,SEG1_TOP_3,THETA1_1,THETA1_2)

%    This function was generated by the Symbolic Math Toolbox version 9.0.
%    16-Jun-2022 14:59:01

t2 = cos(theta1_2);
p_seg1_bottom = [seg1_top_1-l1.*sin(theta1_2),seg1_top_2+l1.*t2.*sin(theta1_1),seg1_top_3-l1.*t2.*cos(theta1_1)];
