function p_seg2_bottom = find_seg2_bottom(l1,l2,seg1_top_1,seg1_top_2,seg1_top_3,theta1_1,theta1_2,theta2_1,theta2_2)
%FIND_SEG2_BOTTOM
%    P_SEG2_BOTTOM = FIND_SEG2_BOTTOM(L1,L2,SEG1_TOP_1,SEG1_TOP_2,SEG1_TOP_3,THETA1_1,THETA1_2,THETA2_1,THETA2_2)

%    This function was generated by the Symbolic Math Toolbox version 9.0.
%    16-Jun-2022 14:59:02

t2 = cos(theta1_2);
t3 = cos(theta2_2);
p_seg2_bottom = [seg1_top_1-l1.*sin(theta1_2)-l2.*sin(theta2_2),seg1_top_2+l1.*t2.*sin(theta1_1)+l2.*t3.*sin(theta2_1),seg1_top_3-l1.*t2.*cos(theta1_1)-l2.*t3.*cos(theta2_1)];
