function f1 = find_f1(alpha1_1,alpha1_2,g,lg1,m1,omega1_1,omega1_2,seg1_top_a_1,seg1_top_a_2,seg1_top_a_3,theta1_1,theta1_2)
%FIND_F1
%    F1 = FIND_F1(ALPHA1_1,ALPHA1_2,G,LG1,M1,OMEGA1_1,OMEGA1_2,SEG1_TOP_A_1,SEG1_TOP_A_2,SEG1_TOP_A_3,THETA1_1,THETA1_2)

%    This function was generated by the Symbolic Math Toolbox version 9.0.
%    16-Jun-2022 12:02:54

f1 = [m1.*(seg1_top_a_1-alpha1_2.*lg1.*cos(theta1_2)+lg1.*omega1_2.^2.*sin(theta1_2)),-m1.*(-seg1_top_a_2+lg1.*omega1_1.^2.*cos(theta1_2).*sin(theta1_1)+lg1.*omega1_2.^2.*cos(theta1_2).*sin(theta1_1)-alpha1_1.*lg1.*cos(theta1_1).*cos(theta1_2)+alpha1_2.*lg1.*sin(theta1_1).*sin(theta1_2)+lg1.*omega1_1.*omega1_2.*cos(theta1_1).*sin(theta1_2).*2.0),m1.*(g+seg1_top_a_3+lg1.*omega1_1.^2.*cos(theta1_1).*cos(theta1_2)+lg1.*omega1_2.^2.*cos(theta1_1).*cos(theta1_2)+alpha1_1.*lg1.*cos(theta1_2).*sin(theta1_1)+alpha1_2.*lg1.*cos(theta1_1).*sin(theta1_2)-lg1.*omega1_1.*omega1_2.*sin(theta1_1).*sin(theta1_2).*2.0)];
