function G_hirashima = find_G_hirashima(lg1,m1,theta1_1,theta1_2)
%find_G_hirashima
%    G_hirashima = find_G_hirashima(LG1,M1,THETA1_1,THETA1_2)

%    This function was generated by the Symbolic Math Toolbox version 9.0.
%    16-Jun-2022 12:02:54

G_hirashima = [-lg1.*m1.*cos(theta1_2).*sin(theta1_1);-lg1.*m1.*sin(theta1_2);0.0];
