function G_hirashima = find_G_hirashima(l1,lg1,lg2,m1,m2,theta1_1,theta1_2,theta2_1,theta2_2)
%find_G_hirashima
%    G_hirashima = find_G_hirashima(L1,LG1,LG2,M1,M2,THETA1_1,THETA1_2,THETA2_1,THETA2_2)

%    This function was generated by the Symbolic Math Toolbox version 9.0.
%    16-Jun-2022 12:22:23

G_hirashima = [-m2.*(l1.*cos(theta1_2).*sin(theta1_1)-lg1.*cos(theta1_2).*sin(theta1_1))-lg1.*cos(theta1_2).*sin(theta1_1).*(m1+m2);-m2.*(l1.*sin(theta1_2)-lg1.*sin(theta1_2))-lg1.*sin(theta1_2).*(m1+m2);0.0;-lg2.*m2.*cos(theta2_2).*sin(theta2_1);-lg2.*m2.*sin(theta2_2);0.0];
