function f2 = find_f2(alpha1_1,alpha1_2,alpha2_1,alpha2_2,g,l1,lg2,m2,omega1_1,omega1_2,omega2_1,omega2_2,seg1_top_a_1,seg1_top_a_2,seg1_top_a_3,theta1_1,theta1_2,theta2_1,theta2_2)
%FIND_F2
%    F2 = FIND_F2(ALPHA1_1,ALPHA1_2,ALPHA2_1,ALPHA2_2,G,L1,LG2,M2,OMEGA1_1,OMEGA1_2,OMEGA2_1,OMEGA2_2,SEG1_TOP_A_1,SEG1_TOP_A_2,SEG1_TOP_A_3,THETA1_1,THETA1_2,THETA2_1,THETA2_2)

%    This function was generated by the Symbolic Math Toolbox version 9.0.
%    16-Jun-2022 12:22:24

mt1 = [m2.*(seg1_top_a_1-alpha1_2.*l1.*cos(theta1_2)-alpha2_2.*lg2.*cos(theta2_2)+l1.*omega1_2.^2.*sin(theta1_2)+lg2.*omega2_2.^2.*sin(theta2_2)),-m2.*(-seg1_top_a_2+l1.*omega1_1.^2.*cos(theta1_2).*sin(theta1_1)+l1.*omega1_2.^2.*cos(theta1_2).*sin(theta1_1)+lg2.*omega2_1.^2.*cos(theta2_2).*sin(theta2_1)+lg2.*omega2_2.^2.*cos(theta2_2).*sin(theta2_1)-alpha1_1.*l1.*cos(theta1_1).*cos(theta1_2)-alpha2_1.*lg2.*cos(theta2_1).*cos(theta2_2)+alpha1_2.*l1.*sin(theta1_1).*sin(theta1_2)+alpha2_2.*lg2.*sin(theta2_1).*sin(theta2_2)+l1.*omega1_1.*omega1_2.*cos(theta1_1).*sin(theta1_2).*2.0+lg2.*omega2_1.*omega2_2.*cos(theta2_1).*sin(theta2_2).*2.0)];
mt2 = [m2.*(g+seg1_top_a_3+l1.*omega1_1.^2.*cos(theta1_1).*cos(theta1_2)+l1.*omega1_2.^2.*cos(theta1_1).*cos(theta1_2)+lg2.*omega2_1.^2.*cos(theta2_1).*cos(theta2_2)+lg2.*omega2_2.^2.*cos(theta2_1).*cos(theta2_2)+alpha1_1.*l1.*cos(theta1_2).*sin(theta1_1)+alpha1_2.*l1.*cos(theta1_1).*sin(theta1_2)+alpha2_1.*lg2.*cos(theta2_2).*sin(theta2_1)+alpha2_2.*lg2.*cos(theta2_1).*sin(theta2_2)-l1.*omega1_1.*omega1_2.*sin(theta1_1).*sin(theta1_2).*2.0-lg2.*omega2_1.*omega2_2.*sin(theta2_1).*sin(theta2_2).*2.0)];
f2 = [mt1,mt2];
